### ISSUE TITLE
Swashes overlap marks in following clusters

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tai-viet#6]
### Font
NotoSansTaiViet-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/tai-viet/releases/tag/NotoSansTaiViet-v2.002
Date: 2022-09-26

### Font version
Version 2.002

### Issue
Letters with long rightwards swashes can overlap marks in following clusters.

### Character data
ꪤꪤꪳꪤꪸ
U+AAA4 TAI VIET LETTER LOW YO
U+AAA4 TAI VIET LETTER LOW YO
U+AAB3 TAI VIET VOWEL UE
U+AAA4 TAI VIET LETTER LOW YO
U+AAB8 TAI VIET VOWEL IA

### Screenshot
![ꪤꪤꪳꪤꪸ](https://user-images.githubusercontent.com/1124347/192302722-6b9d7b3e-4888-4110-8c92-1b21846ca8b2.png)

**Comment by dscorbett** [comment]
Some swashes still overlap, as in <U+AA8F TAI VIET LETTER HIGH SO, U+AAA4 TAI VIET LETTER LOW YO, U+AAB3 TAI VIET VOWEL UE>:
![ꪏꪤꪳ](https://github.com/notofonts/tai-viet/assets/1124347/8e5d6170-7ec6-48dd-8f60-5dc349631941)

**Comment by simoncozens** [comment]
I've added a few more glyphs to the list of swashy glyphs, which should fix this.
![shape](https://github.com/notofonts/tai-viet/assets/106728/0dea26e0-d642-4ef4-b2c9-006ffe309a2d)
